#!/usr/bin/env python3
import os
import sys
import itertools

from math import prod

def eprint(*args, **kwargs):
    print(*args, file=sys.stderr, **kwargs)

import datetime

import hashlib

import tomlikey as tomli

class Config:
    def __init__(self, name, path):
        self.name = name
        self.path = path
        self.reset()

    def reset(self):
        self.hash = None
        self.rawfile = None
        self.rawfileCS = None
        
    def __str__(self):
        return f"C:{self.name}"

    def __repr__(self):
        return f"[C:{self.name}:{self.path}]"

    def load(self):
        # Read whole file for storage
        with open(self.path,"rb") as file:
            self.rawfile = file.read()
        eprint("CONFIGLEN =",len(self.rawfile),"FOR",self.path)

        # Save its hash for checking
        h = hashlib.sha256()
        h.update(self.rawfile)
        self.rawfileCS = h.digest()
        
        # Parse it using dtomlib
        self.hash = tomli.loads(self.rawfile.decode())

    def getFileBytes(self):
        return self.rawfile

    def getFileChecksum(self):
        return self.rawfileCS

    def getRequiredSection(self,name):
        assert name in self.hash, f"Unknown section {name}"
        return self.hash[name]
        
    def getOptionalSection(self,name):
        return self.hash.get(name, None)

    def getInitializedSection(self,name,value):
        have = self.getOptionalSection(name)
        if not have:
            self.hash[name] = value
        return self.getRequiredSection(name)

from pprint import pprint

def xbname(name):
    return "XBlock_"+name

def tapidxname(name):
    if name == "NONE":
        raise Exception("Cannot name a TAP 'NONE'!")
    return "cTAPIDX_"+name

def genSymbol(name):
    return name[0:2]

def addc(*arg):
    return tuple(sum(t) for t in zip(*arg))

def mulc(*arg):
    return tuple(prod(t) for t in zip(*arg))

def smulc(scalar,tup):
    return [ scalar * t for t in tup ]

def saddc(scalar,tup):
    return [ scalar + t for t in tup ]


class Main:
    def __init__(self,name,brainFile,spineFile,gripFile,codeFile):
        self.name = name
        eprint("__main__",self.name)
        self.configPath = self.findConfigOrDie(brainFile)
        self.brainCfg = self.loadConfig(self.configPath)
        self.spineCfg = self.loadConfig(spineFile)
        self.gripCfg = self.loadConfig(gripFile)
        self.codeCfg = self.loadConfig(codeFile)

    def mapDir(self,dir):
        if dir == 'N':
            return [0,-1]
        if dir == 'S':
            return [0,1]
        if dir == 'E':
            return [1,0]
        if dir == 'W':
            return [-1,0]
        raise ValueError('illegal dir',dir)

    def oppDir(self,dir):
        if dir == 'N':
            return 'S'
        if dir == 'S':
            return 'N'
        if dir == 'E':
            return 'W'
        if dir == 'W':
            return 'E'
        raise ValueError('illegal dir',dir)

    def growDir(self,dir):      # Direction dir taps are laid out
        if dir == 'N':
            return 'E'
        if dir == 'S':
            return 'W'
        if dir == 'E':
            return 'S'
        if dir == 'W':
            return 'N'
        raise ValueError('illegal dir',dir)
    
    def makeTapsList(self):
        taps = self.taps
        self.tapslist = []
        count = 0
        for t in ('sensor','motor','hidden'):
            for k,v in taps[t].items():
                c = count
                count = count + 1
                v['number'] = c
                name = v.get('name',"")
                self.tapslist.append((k,t,name,c))
        eprint("PSOD",self.tapslist)

    def generate(self):
        print(f"//AUTOGENERATED ON {datetime.datetime.now()} DO NOT EDIT")
        xb = self.brainCfg.getRequiredSection("xblock")
        print('''
@Concrete
transient BeeveeBIMXBlock : BrainInfoMapXBlock {
  constant ClassId cXBClassIds[] = {''')
        count = 0
        for k,v in xb.items():
            v['number'] = count
            count = count + 1
            print(f"    {xbname(k)}.classidof,")
        print('''    0 // unused, illegal
  }; // cXBClassIds''')

        print(f'''
  // Generated from {self.spineCfg!r}
  // and {self.brainCfg!r}
  constant ClassId cTAPClassIds[] = {{''')
        count = 0
        for (k,t,name,c) in self.tapslist:
            print(f"    {k}.classidof,  //< {c} {t} {name}")
        print('''  }; // cTAPClassIds''')
        print(f'''
  // Names for constant TapIdxs''')
        for (k,t,name,c) in self.tapslist:
            tname = tapidxname(k)
            print(f"  constant TapIdx {tname} = {c}u; //< {name}")
        #eprint(f'DFLSP {self.tapslist}')
        print('''
  constant String cTAPNames[] = {''')
        for name,type,desc,c in self.tapslist:
            print(f"    \"{name}\",  //< {c} {t} {desc}")
        print('''  }; // cTAPNames''')

        print('''
  //// BrainInfoMap API
  @Override Unsigned getXBCount() { return cXBClassIds.lengthof - 1u; }
  @Override Unsigned getXBlockIndexAtOrigin(C2D absc) {''')
        for k,v in xb.items():
            print(f'''\
    if (absc == {xbname(k)}.cXBI_POS) return {v['number']}u;\
''')
        print('''\
    return Unsigned.maxof;
  }''')
        print('''
  @Override ClassId getXBlockClassIdFromIndex(Unsigned xblockIdx) {
    return cXBClassIds[xblockIdx];
  }

  @Override ClassId getTAPClassIdFromTapIdx(Unsigned tapidx) {
    return cTAPClassIds[tapidx]; // or fail if tapidx >= cTAPClassIds.lengthof
  }

  @Override Unsigned getTAPCount() {
    return cTAPClassIds.lengthof;
  }

  @Override Unsigned getTapIdxFromClassId(ClassId cid) {
    for (Unsigned i = 0u; i < cTAPClassIds.lengthof; ++i) {
      if (cid == cTAPClassIds[i])
        return i;
    }
    return Unsigned.maxof;
  }

  @Override String getTAPNameFromTapIdx(Unsigned tapidx) {
    String ret;  // null by default
    if (tapidx < cTAPNames.lengthof) ret = cTAPNames[tapidx];
    return ret;
  }
''')
        print('}')

        for k,v in xb.items():
            self.analyzeXBlock(k,v)

        for k,v in xb.items():
            self.generateXBlock(k,v)

    def generateGripRouter(self):
        count = len(self.gripinfo)
        print(f'''
@Concrete
quark BeeveeGrips : Grips {{''')        
        for k,n in zip(self.gripinfo.keys(),itertools.count()):
            print(f'''  constant Unsigned cGRIPIDX_{k} = {n}u; ''')
        print(f'''
  constant ClassId cALL_GRIPS[] = {{''')
        for k,[alldests,startidxs] in self.gripinfo.items():
            print(f'''    GripRouting_{k}.classidof,''')
        print(f'''  }};''')

        print(f'''
  @Override Unsigned getGripsCount() {{ return cALL_GRIPS.lengthof; }}
  @Override ClassId getGripRoutingClassIdFromIndex(Unsigned gripidx) {{
    return cALL_GRIPS[gripidx];
  }}
}}''')

    def generateSigFuncFor(self,gripname):
        (sigfunctions,sigmaps) = ("","")
        gcfg = self.gripCfg
        grips = gcfg.getRequiredSection('grip')
        grip = grips.get(gripname)
        if not grip:
            return (sigfunctions,sigmaps)
        for funk in grip.get('sigfunc',{}):
            code = grip['sigfunc'][funk]
            func = f'''
  Int sigFunc{funk} (Int i) {{
     Int o = i;
     {{ {code} }}
     return o;
 }}
'''            
            sigfunctions += func
        for srck in grip.get('sigmap',{}):
            thismap = f'''
  if (src == BeeveeBIMXBlock.{tapidxname(srck)}) {{'''
            dsts = grip['sigmap'][srck];
            for dstk in dsts:
                thismap += f'''
    if (dst == BeeveeBIMXBlock.{tapidxname(dstk)}) {{
      return sigFunc{dsts[dstk]}(i);
    }}
'''                
            thismap += f'''    return o;
  }}'''
            sigmaps += thismap

        return (sigfunctions,sigmaps)

    def generateGripInfo(self):
        for k,[alldests,startidxs] in self.gripinfo.items():
            print(f'''
@Concrete
element GripRouting_{k} : GripRouting {{
  //// GripRouting API
  @Override String getGripName() {{ return "{k}"; }}
  @Override Unsigned getDestCount(TapIdx src) {{
    return cFIRST_DEST_INDEX[src+1u] - cFIRST_DEST_INDEX[src];
  }}
  @Override TapIdx getDest(TapIdx src, Unsigned idx) {{
    if (idx >= getDestCount(src)) fail(__FILE__,__LINE__);
    return cALL_DESTS[cFIRST_DEST_INDEX[src] + idx];
  }}
  //@Override Unsigned getSrcCount(TapIdx dest) ;
  //@Override TapIdx getSrc(TapIdx dest, Unsigned idx) ;

  constant TapIdx cALL_DESTS[] = {{''')
            for (dest,num,tap) in alldests:
                print(f'    BeeveeBIMXBlock.{tapidxname(dest)},  //< dest {num} of {tap}')
            print(f'  }}; // cALL_DESTS')

            print(f'''
  constant Unsigned cFIRST_DEST_INDEX[] = {{''')
            for (sidx,tap,doc) in startidxs:
                print(f'    {sidx}u,  //< start idx of {tap} {doc}')
            print(f'  }}; // cFIRST_DEST_INDEX')

            ## generate signal mapping code
            (sigfuncs,sigmaps) = self.generateSigFuncFor(k)

            print(f'''{sigfuncs}

  @Override Bool mapSig(TapIdx src, TapIdx dst, Int input, Int & output) {{
    output = mapAllSigs(src,dst,input);
    return true;
  }}

  Int mapAllSigs(TapIdx src, TapIdx dst, Int i) {{
    Int o = i;
    {sigmaps}
  return o;
  }}
''')
            print(f'}} // GripRouting_{k}')

    def findCorner(self,ind,outd):
        if ind == 'N' and outd == 'E' or ind == 'E' and outd == 'N':
            return 'NE'
        if ind == 'N' and outd == 'W' or ind == 'W' and outd == 'N':
            return 'NW'
        if ind == 'S' and outd == 'W' or ind == 'W' and outd == 'S':
            return 'SW'
        if ind == 'S' and outd == 'E' or ind == 'E' and outd == 'S':
            return 'SE'
        raise ValueError('Bad corner',ind,outd)

    def analyzeXBlock(self,name,props):
        xbpos = props['pos']
        # Derive size
        cols = max(len(props['taps']['N']),len(props['taps']['S']))
        rows = max(len(props['taps']['E']),len(props['taps']['W']))
        eprint("BONGSNI",name,cols,rows)

        props['origin'] = 'NW'

        w = cols
        h = rows
        #props['size'] = [w+2,h+2]
        props['size'] = [w,h]  ## NOT INCLUDING SURROUNDING TAPS!?
        stride = props['stride']
        sw = stride[0]*w+2
        sh = stride[1]*h+2
        hc3w = int((sw+2)/3)
        hc3h = int((sh+2)/3)
        props['hc3size'] = [hc3w,hc3h]
        eprint("ZANSNI",name,props,cols,rows,stride,hc3w,hc3h)

        for side in ('N','S','E','W'):
            offset = self.mapDir(self.growDir(side))
            eprint("ZANS11",side,offset)

            count = 0
            for tap in props['taps'][side]:
                count = count+1
                tappos = addc(smulc(count,offset),xbpos)
                self.generateTAP(tap,name,count,tappos)

    def generateTAP(self,tapname,xbname,num,tappos):
        taps = self.brainCfg.getInitializedSection("tap",{})
        if not tapname in taps:
            taps[tapname] = {}
        tap = taps[tapname]
        if not 'uses' in tap:
            tap['uses'] = {}
        uses = tap['uses']
        if not tapname in uses:
            uses[xbname] = [tappos,num]
        print(f'// {tap} TAP {tapname} #{num} in {xbname} at {tappos}')

    def getRelBox(self,side,size):
        if side == 'W':
            return ((0,1),(1,size[1]-1))
        if side == 'N':
            return ((1,0),(size[0]-1,1))
        if side == 'S':
            return ((1,size[1]-1),(size[0]-1,size[1]))
        if side == 'E':
            return ((size[0]-1,1),(size[0],size[1]-1))
        raise ValueError('Bad side',side)
        
    def generateFeedDirCode(self,props):
        print(f'''// generateFeedDirCode({props})
  @Override
  virtual Bool getXBInfoFeedDir(C2D relc, AxialDir & feedad, Bool & isinput) {{\
''')
        for side,isinput in (('indir','true'), ('outdir','false')):
            dir = props[side]
            relbox = self.getRelBox(dir,props['size'])
            print(f'''\
    mD&&pR("GFDCD{side}10")&&pR(relc);
    if (relc.x >= {relbox[0][0]} && relc.y >= {relbox[0][1]} &&
        relc.x <  {relbox[1][0]} && relc.y < {relbox[1][1]}) {{
      feedad = c{dir};
      isinput = {isinput};
      return true;
    }}
    mD&&pR("GFDCD{side}11");
''')
        print('''\
    return false;
  }
''')

    def generateAxonTargetCode(self,props):
        print(f'''// generateAxonTargetCode({props})
  @Override
  virtual TapIdx getXBInfoAxonTarget(TapIdx tapidx) {{
    BeeveeBIMXBlock bim;
    ClassId fromid = bim.getTAPClassIdFromTapIdx(tapidx);\
''')
        for tfrom,tto in props.get('axons',[]):
            print(f'''\
    if (fromid == {tfrom}.classidof) return (TapIdx) bim.getTapIdxFromClassId({tto}.classidof);\
''')
        print('''\
    return cTAPIDX_NONE;
  }
''')

    def generateTAPCheckCode(self,var,svar,side,vec,props):
        relbox = self.getRelBox(props[side],props['size'])
        print(f'// generateTAPCheckCode({side},{vec},{props}) {relbox}')
        print(f'''\
    mD&&pR("GXBIT{side}10")&&pR({var});
    if ({svar} &&
        {var}.x >= {relbox[0][0]} && {var}.y >= {relbox[0][1]} &&
        {var}.x <  {relbox[1][0]} && {var}.y < {relbox[1][1]}) {{
      C2D diff((C2D.Coord) ({var}.x-{relbox[0][0]}),(C2D.Coord) ({var}.y-{relbox[0][1]}));
      Unsigned idx = diff.length();\
      mD&&pR("GXBIT{side}11")&&pR(diff)&&pR(idx);
''')
        if vec == 'inputs':
            avar = 'cIN_TAPS'
        elif vec == 'outputs':
            avar = 'cOUT_TAPS'
        else:
            raise ValueError('bad vec',vec)
        print(f'''\
      return {avar}[idx];            
    }}''')
    
    def generateXBlock(self,name,props):
        n = xbname(name)
        stride = props['stride']
        size = props['size'];
        intentionClass = props.get('intentionClass','DefaultXBlockState')
        originsn = props.get('originSN',5)
        symbol = props.get('symbol',genSymbol(name))
        color = props.get('color','#fff')
        print(f'''
//NAME {n} IS {props}
/** {n}.
   \\symbol {symbol}
   \\color {color}
 */
@Concrete
element {n} : {n}_BASE + FourWaySlots {{
  typedef XBlockStgT({size[0]}u,{size[1]}u,{stride[0]}u,{stride[1]}u) {n}_BASE;

  //// URSELF API  
  @Override Void behave() {{ pursueIntention(); }}\
''')
        (w,h) = props['size']
        print(f'''
  constant Unsigned cSIDE_LENGTHS[4] = {{ {h}, {w}, {w}, {h} }};''')
        startIdxs = (0,h,h+w,h+w+w)
        print(f'''
  // Starting indices in cTAPS_BY_SIDE for each side
  constant Unsigned cSIDE_TAPIDX[4] = {{\
''', end='')
        print(*startIdxs, sep=", ", end='');
        print("}; //< [0] W, [1] N, [2] S, [3] E")
        #eprint("BONSEI",w,h);
        print(f'''\
  constant TapIdx cTAPS_BY_SIDE[] = {{\
''')
        count = 0
        for side in ('W','N','S','E'):
            if side == 'W' or side == 'E':
                slen = h
            else:
                slen = w
            taps = props['taps'][side]
            #eprint("BONSEI",taps);
            tlen = len(taps)
            for idx in range(slen):
                if idx < tlen and taps[idx] != '_':
                    val = tapidxname(taps[idx])+','
                else:
                    val = 'cTAPIDX_HEMP,';
                val = 'BeeveeBIMXBlock.' + val
                print(f'    {val:<20}  //{count:>3}: {side} #{idx}')
                count = count+1
        print(f'''\
  }}; // cTAPS_BY_SIDE''')

        print(f'''
  constant Unsigned cXBLOCK_INDEX = {props['number']}u;
        
  constant PocketDir cXBI_ORIGIN = cQUAD_{props['origin']};

  constant C2D cXBI_GRID_SIZE = {{ .x = {props['size'][0]}, .y = {props['size'][1]} }}; //< INTERNAL GRID SIZE
  constant C2D cXBI_GRID_STRIDE = {{ .x = {props['stride'][0]}, .y = {props['stride'][1]} }}; //< GRID STRIDE

  constant C2D cXBI_POS = {{ .x = {props['pos'][0]}, .y = {props['pos'][1]} }}; //< HC3 POS
  constant C2D cXBI_SIZ = {{ .x = {props['hc3size'][0]}, .y = {props['hc3size'][1]} }}; //< HC3 SIZ

  //// Intender API
  @Override Unsigned getIntentionClass() {{ return {intentionClass}.classidof; }}

  //// XBlock API
  @Override Unsigned getXBlockIndex() {{ return cXBLOCK_INDEX; }}
  @Override C2D getXBlockSize() {{ return cXBI_GRID_SIZE; }}
  @Override C2D getXBlockStride() {{ return cXBI_GRID_STRIDE; }}
  @Override C2D getXBlockOrigin() {{ return getXBInfoPosition(); }}
  @Override SN getOriginSN() {{ return {originsn}u; }}

  //// XBInfo API 
  @Override String getXBInfoName() {{ return "{name}"; }}
  @Override C2D getXBInfoPosition() {{ return cXBI_POS; }}
  @Override C2D getXBInfoSize() {{ return cXBI_SIZ; }}
  @Override PocketDir getXBInfoOrigin() {{ return cXBI_ORIGIN; }}

''')
        #self.generateFeedDirCode(props)
        self.generateAxonTargetCode(props)
        
        print(f'''
  //// XBInfo API
  @Override ClassId getXBInfoXBlockClass() {{ return self.classidof; }}
  @Override Bool getXBInfoFeedDir(C2D relc, AxialDir & feedad, Bool & isinput) {{
     fail(__FILE__,__LINE__,"WHY DO I EXIST? #METOO");
     return false;
  }}
        
  @Override
  virtual TapIdx getXBInfoSideTAP(C2D relc, AxialDir side) {{
    Int c = -1;
    if (side == cW || side == cE) c = relc.getY();
    else if (side == cN || side == cS) c = relc.getX();
    if (c < 0 || ((Unsigned) c) >= cSIDE_LENGTHS[side]) return 0u;
    return cTAPS_BY_SIDE[cSIDE_TAPIDX[side]+(Unsigned) c];
  }}
''')
        print(f'}} // {n}')

    def generateOutput(self):
        cfg = self.brainCfg
        csect = cfg.getRequiredSection("Config") # ensure exists?
        self.generate()
        self.generateGripRouter()
        self.generateGripInfo()
        self.generateCode()

    def findConfigOrDie(self,optPath):
        paths = []
        if optPath != None:
            paths.append(optPath)
        # e = os.environ
        # ekey ='BEEVEESOURCESPATH'
        # if ekey in e:           # First try environmental variable
        #     paths.append(e[ekey])
        # paths.append('../code/BVBrain.cfg') # Then 'std loc'
        # paths.append('./BVBrain.cfg')       # Last ditch
        for p in paths:
            (exists,path) = self.expandPath(p)
            if exists:
                eprint(f"Found config file {path}")
                return path
        self.die(f"Config file not found in {paths}")

    def expandPath(self,path):
        epath = os.path.expanduser(path)
        if os.path.exists(epath):
            return (True,epath)
        return (False,None)

    def die(self,message):
        eprint(f"Error: {message}")
        exit(2)

    def loadConfig(self,path):
        if os.path.isfile(path):
            ret = Config("Cfg",path)
        else:
            self.die(f"Can't load {path}")
        ret.load()
        return ret

    def analyzeSpineTAPs(self):
        scfg = self.spineCfg
        terms = scfg.getRequiredSection('term')
        self.taps = dict(sensor= {}, motor= {}, hidden= {})
        for k,v in terms.items():
            if v.get('disabled',0) == 1:
                continue
            eprint(f'STUFFJDKDKD {k}:{v}')
            t = v['type']
            if t == 'sensor' or t == 'motor':
                self.taps[t][k] = {'name': v.get('name'), 'doc': v.get('doc',"")}
        eprint(f'zongdK {self.taps}')

    def mergeBrainTAPs(self):
        xb = self.brainCfg.getRequiredSection("xblock")
        for k,v in xb.items():  # per xb
            if not v.get("taps",None):
                v["taps"] = {}
            taps = v["taps"]    # per xb
            eprint(f'BAHOOM {k},{v},{taps}')
            for side in ('N','S','E','W'):
                if not taps.get(side,None):
                    taps[side] = []
            for side,list in taps.items():
                for tap in (*list,'_'):   # make sure HEMP declared even if dtoml doesn't use it..
                    if tap == "_":
                        tap = 'HEMP' # Hidden EMPty
                    eprint(f'NARG {tap},{k},{side}')
                    # add as hidden if not found as sensor or motor
                    if self.taps['sensor'].get(tap) == None and self.taps['motor'].get(tap) == None:
                        self.taps['hidden'][tap] = {'name': tap, 'doc': f'xblock.{k} {v}'}
                        eprint(f'NARGL {self.taps["hidden"][tap]}')
        eprint(f'MERGBNONIC {self.taps}')

    def analyzeGripInfoFor(self,grip,vals,defgrip):
        alldests = []
        startidxs = []
        routes = vals.get('routes',{})
        defroutes = defgrip.get('routes',{})
        eprint(f'ANGIF {grip} {vals} {defgrip} ROUTES {routes} &&&&&&&&&&&&&&&& {self.tapslist}')
        for (tap,t,name,c) in self.tapslist:   # for all taps 'tap'
            startidxs.append((len(alldests),tap,name))
            thisdests = {}
            for dest in itertools.chain(routes.get(tap,[]),defroutes.get(tap,[])):
                eprint(f'FUGNO {tap} {dest} {len(startidxs)} {len(alldests)}')
                if not thisdests.get(dest,None):
                    alldests.append((dest,len(thisdests),tap))
                    thisdests[dest] = True
                    eprint(f'DLKUGNO {dest} {thisdests}')
        startidxs.append((len(alldests),'final','dummy for end of list'))  # one extra to end the last set
        self.gripinfo[grip] = [ alldests, startidxs]
        eprint(f'IIIEIEIIE {grip} :: {self.gripinfo[grip]}')
        
    def mergeGripInfo(self):
        gcfg = self.gripCfg
        grips = gcfg.getRequiredSection('grip')
        self.gripinfo = {}  # name->[ [all dests], [start idxes] ]
        #eprint(f'GRISLD {grips}')
        defgrip = grips.get('_',{})
        for k,v in grips.items():
            if k == '_':
                continue
            self.analyzeGripInfoFor(k,v,defgrip)

    def analyzeConstant(self,tok):
        if not self.codeConstVals.get(tok):
            self.codeConstVals[tok] = []

    def analyzeOperator(self,tok):
        if not self.codeOps.get(tok):
            self.codeOps[tok] = {}

    def analyzeFunction(self,tok):  # function use
        if not self.codeFuncAddrs.get(tok):
            self.codeFuncAddrs[tok] = None
            

    def analyzeToken(self,tok,funcinfo):
        if funcinfo:
            self.codeIntRam.append((tok,*funcinfo))
        else:
            self.codeIntRam.append(tok)
        if type(tok)==int:
            return
        code = tok[0]
        if code == 'c':
            self.analyzeConstant(tok)
        elif code == 'o':
            self.analyzeOperator(tok)
        elif code == 'f':
            self.analyzeFunction(tok)

    def analyzeCodeInfoFor(self,func,vals):
        eprint(f'ANCIF {func} {vals}')
        funcaddr = len(self.codeIntRam)
        exist = self.codeFuncAddrs.get(func)
        if exist:
            raise Exception(f"MULTIPLY DEFINED FUNCTION: {func} {vals}")
        self.codeFuncAddrs[func] = funcaddr
        first = (func,vals.get('doc',None))
        self.codeFunctions[func] = first[1]
        self.analyzeToken('oENTER',first)
        last = None
        for tok in vals['code']:
            self.analyzeToken(tok,None)
            last = tok
        if last != 'oRETURN':
            self.analyzeToken('oRETURN',('From',func))
        
    def mergeCodeInfo(self):
        ccfg = self.codeCfg
        funcs = ccfg.getRequiredSection('function')
        self.codeIntRam = [('oCALL','fake for returning to top level')]  # list of code ints
        self.codeFunctions = {}  # name -> doc
        self.codeFuncAddrs = {}  # name -> intramaddr
        self.codeConstVals = {}  # name -> constval
        self.codeOps = {}        # name -> ??
        for k,v in funcs.items():
            self.analyzeCodeInfoFor(k,v)

        eprint(f"EXPOC {self.codeIntRam}")
        eprint(f"EXPFAD {self.codeFuncAddrs}")
        eprint(f"EXPCNV {self.codeConstVals}")
        eprint(f"EXPOXS {self.codeOps}")
        eprint(f'CODELD {funcs}')

        ops = ccfg.getRequiredSection('operator')
        eprint(f'OPSPOPS {ops}')

        for k in self.codeOps:
            if not k in ops:
                raise Exception("Undeclared operator:",k)
        for k,v in ops.items():
            if not v.get('impl'):
                v['impl'] = f'return native_{k}(s,g,t,l)'
            eprint(f"DIDIMPL {k},{v}")

    def analyzeTRAKtInfoFor(self,t,vals):
        eprint(f'ANTIF {t} {vals}')
        traktnum = len(self.traktList)
        exist = self.traktMap.get(t)
        if exist:
            raise Exception(f"MULTIPLY DEFINED FUNCTION: {t} {vals}")
        self.traktList.append(t)
        self.traktMap[t] = { 'index' : traktnum }
        if (k := 'mSpeedLeft') in vals:
            speedNotWheel = False
            v1 = vals[k]
            v2 = vals['mSpeedRight']  # raise exception if missing
        elif (k := 'mSpeedMin') in vals:
            speedNotWheel = True
            v1 = vals[k]
            v2 = vals['mSpeedMax']  # ditto
        else:
            raise Exception(f"unrecognized trakt {t} ({vals})")
        if (k := 'mDoneFunc') in vals:
            funcNotOp = True
            done = vals[k]
        elif (k := 'mDoneOp') in vals:
            funcNotOp = False
            done = vals[k]
        else:
            raise Exception(f"trakt {t} missing done info ({vals})")
        self.traktMap[t]['mSpeedNotWheel'] = speedNotWheel
        self.traktMap[t]['mSpeed1'] = v1
        self.traktMap[t]['mSpeed2'] = v2
        self.traktMap[t]['mFuncNotOp'] = funcNotOp
        self.traktMap[t]['mDoneCode'] = done

    def mergeTRAKtInfo(self):
        ccfg = self.codeCfg
        trakts = ccfg.getRequiredSection('trakt')
        self.traktList = []      # name, ..
        self.traktMap = {}       # name -> {stuff}
        self.codeOps = {}        # name -> ??
        for k,v in trakts.items():
            self.analyzeTRAKtInfoFor(k,v)
        eprint(f"MTKIN10 {self.traktMap}")

            
    def generateTRAKts(self):
        print(f'''
  typedef Unsigned(5) TRAKt; //< traktor act codes
  //// TRAKt CODE NUMBERS''')
        for k in self.traktList:
            tinfo = self.traktMap[k]
            print(f'''  constant TRAKt {k:30} = {tinfo['index']:3}u;''')
        print(f'''  //// END TRAKt CODE NUMBERS''')
        print(f'''  constant Unsigned cTRA_TRAKTNUM_COUNT = {len(self.traktList)}u;''')
        print(f'''
  //// TRAKt CODE NAMES       
  constant String cTRAKT_NAMES[cTRA_TRAKTNUM_COUNT] = {{''')
        for k in self.traktList:
            i = self.traktMap[k]['index']
            print(f'''    {'"'+k+'.'+str(i)+'",':30} // {i:3}''')
        print(f'''  }}; // cTRAKT_NAMES''')
        print(f'''
  String nameOfTRAKtOrNull(TRAKt t) {{
    String ret;
    if (t < cTRA_TRAKTNUM_COUNT) ret = cTRAKT_NAMES[t];
    return ret;
  }}
  String nameOfTRAKt(TRAKt t) {{
    String ret = nameOfTRAKtOrNull(t);
    if (!(Bool) ret) ret = "cTRAUNKNOWN";
    return ret;
  }}
''')        
        print(f'''\
  //// CONSTANT MotorCmd DECLARATIONS
  constant MotorCmd cTRAKT_MOTORCMDS[cTRA_TRAKTNUM_COUNT] = {{''')
        for k in self.traktList:
            m = self.traktMap[k]
            i = m['index']
            print(f'''   {{  .mTRAKtName = {'"'+k+'",'}
      .mTRAKtNumber = {i}u,
      .mSpeedNotWheel = {'true' if m['mSpeedNotWheel'] else 'false'},
      .mSpeed1 = {str(m['mSpeed1'])+',':20} // {'min' if m['mSpeedNotWheel'] else 'left'}
      .mSpeed2 = {str(m['mSpeed2'])+',':20} // {'max' if m['mSpeedNotWheel'] else 'right'}
      .mFuncNotOp = {'true' if m['mFuncNotOp'] else 'false'},
      .mDoneCode = {m['mDoneCode']},
   }},''')
        print(f'''  }}; // cTRAKT_MOTORCMDS''')
        print(f'''
  MotorCmd makeMotorCmdForTRAKt(TRAKt t) {{
    if (t >= cTRAKT_MOTORCMDS.lengthof) fail(__FILE__,__LINE__,"bad motorcmd code");
    return cTRAKT_MOTORCMDS[t];
  }}

  String nameOfMotorCmd(Unsigned motorcmdidx) {{
    String ret = nameOfMotorCmdOrNull(motorcmdidx);
    if (!(Bool) ret) ret = "<ENOMOTC>";
    return ret;
  }}
        
  String nameOfMotorCmdOrNull(Unsigned motorcmdidx) {{
    String ret;
    if (motorcmdidx < cTRAKT_MOTORCMDS.lengthof)
      ret = cTRAKT_MOTORCMDS[motorcmdidx].mTRAKtName;
    return ret;      
  }}''')


    def generateCode(self):
        print(f'''
quark CodeConstants + DTU + Fail + QDebugUtils {{''')
        self.generateRam()
        self.generateFuncAddrs()
        self.generateOps()
        self.generateTRAKts()
        print(f'''
}} // CodeConstants
''')

    def generateRam(self):
        l = len(self.codeIntRam)
        decl = f'constant Int cRAM[{l}]'
        print(f'''
  {decl} = {{''')        
        for (i,n) in zip(self.codeIntRam,range(l)):
            doc = ''
            if type(i) == tuple:
                (i,*doc) = i
            print(f'''    {str(i)+',':20} // {n:3} {': '.join(map(str,doc))}''')
        print(f'''  }}; // {decl}''')        

    def generateFuncAddrs(self):
        print(f'''
  //// FUNCTION ADDRS''')
        for k,v in self.codeFuncAddrs.items():
            d = self.codeFunctions[k]
            print(f'''  constant Int {k:20} = {v:3};   // {d}''')
        print(f'''  //// END FUNCTION ADDRS''')
        print(f'''
  String nameOfFunction(Int funcaddr) {{
    String ret = nameOfFunctionOrNull(funcaddr);
    if (!(Bool) ret) ret = "<ENOMETH>";
    return ret;
  }}
        
  String nameOfFunctionOrNull(Int funcaddr) {{''')
        for k in self.codeFuncAddrs:
            print(f'''    if (funcaddr == {k}) return "{k}";''')
        print(f'''
    String null;
    return null;
  }}''')

    def isSpecialOp(self,op):
        return op == 'oCALL' or op == 'oENTER' or op == 'oRETURN'
    
    def generateOps(self):
        ccfg = self.codeCfg
        ops = ccfg.getRequiredSection('operator')

        print(f'''
  //// OPERATORS
  constant Int cMIN_OP_VAL = -2000000000;
        ''')
        last = 'cMIN_OP_VAL'
        for k in ops:
            doc = self.codeOps.get(k,'')
            print(f'''  constant Int {k:20} = {last+' + 1;':20}// {doc}''')
            last = k
        print(f'''  constant Int oLAST_OP_USED = {last};''')
        print(f'''  //// END OPERATORS''')

        print(f'''
  //// OPERATOR NAMES
  constant String cOPERATOR_NAMES[] = {{''')
        for k in ops:
            doc = self.codeOps.get(k,'')
            print(f'''  "{k}", // {doc}''')
        print(f'''
 }};  //// END cOPERATOR_NAMES[]''')
        print(f'''
  String nameOfOperatorOrNull(Int op) {{
    Unsigned idx = (Unsigned) (op - cMIN_OP_VAL - 1);
    String ret; // null to start
    if (idx < cOPERATOR_NAMES.lengthof) ret = cOPERATOR_NAMES[idx];
    return ret;
 }}
  String nameOfOperator(Int op) {{
    String ret = nameOfOperatorOrNull(op);
    if (!(Bool) ret) ret = "#";
    return ret;
 }}''')
        
        
        print(f'''
  Bool readRAM(Int addr, Int & res) {{
    if (addr < 0 || addr >= cRAM.lengthof) return false;
    res = cRAM[addr];
    return true;
  }}

  Bool setPC(Int & pc, Int newval) {{
    if (newval < 0 || newval >= cRAM.lengthof) return false;
    pc = newval;
    return true;
  }}''')
        print(f'''
  //// OPERATOR EVAL
  Bool evaluateThisOperatorOnly(Int o, Function & s, GTCC & g, LOCZ & l, TRAKtor & t) {{
    mD&&pR("ETOPO10")&&pR(o);
    if (o >= cFOC_MIN_IMMEDIATE && o <= cFOC_MAX_IMMEDIATE) {{
      Bool ret = s.push(o);
      mD&&s.pRStack("ETOPO11");
      return ret;
    }}
    Int v[3]; // temps
    mD&&pR("ETOPO12")&&pR(nameOfOperator(o));
    mD&&s.pRStack("ETOPO13");
    which(o) {{''')
        for k,v in ops.items():
            if self.isSpecialOp(k):
                continue
            impl = v['impl']
            print(f'''\
    case {k}: {{ {impl}; }}''')
        print(f'''    }}
    s.pRStack("ETOPOMISS")&&pR(o)&&pR(nameOfOperator(o));
    fail(__FILE__,__LINE__); 
    return false; // NOT REACHED
  }}''')

        print(f'''
  Bool isSpecialOp(Int o) {{
    return o == oCALL ||
           o == oENTER ||
           o == oRETURN;
  }}

  Bool evaluateOperator(Int & pc, Function & s, GTCC & g, LOCZ & l, TRAKtor & t) {{
    mD&&pR("EVLOP10")&&pR(pc);
    Int v[3]; // temps
    Int o;
    if (!readRAM(pc,o)) return false;
    pc++;
    mD&&s.pRStack("EVLOP12")&&pR(nameOfOperator(o));
    /// handle 'special ops' here
    which(o) {{''')
        for k,v in ops.items():
            if not self.isSpecialOp(k):
                continue
            impl = v['impl']
            print(f'''\
    case {k}: {{ {impl}; }}''')
        print(f'''
    /// else dish to general case
    otherwise: {{ return evaluateThisOperatorOnly(o, s, g, l, t); }}
    }}
    return false; // NOT REACHED
  }} // OPERATOR EVAL
''')
        
if __name__ == '__main__':

    import sys
    argc = len(sys.argv)
    if argc <= 4 or argc > 5:
        sys.exit("Usage: " + __file__ + " BRAINCONFIGFILE SPINECONFIGFILE GRIPINFOFILE CODEFILE")
    brainFile = sys.argv[1]
    spineFile = sys.argv[2]
    gripFile = sys.argv[3]
    codeFile = sys.argv[4]

    print("// RUNNING",__file__ ,"\n// ON",brainFile,"\n// AND",spineFile,"\n// AND",gripFile,"\n// AND",codeFile,"---")
    mr = Main("ZONGProd",brainFile,spineFile,gripFile,codeFile)
    mr.analyzeSpineTAPs()
    mr.mergeBrainTAPs()
    mr.makeTapsList()
    mr.mergeGripInfo()
    mr.mergeCodeInfo()
    mr.mergeTRAKtInfo()
    mr.generateOutput()
